#!/bin/bash
echo "-- Mise en place de l'environnement de test --"

echo "Démarrage du Cube"
python /home/pi/LeCubeMedia/src/lecube/main.py -c /home/pobot/LeCubeMedia/src/lecube/lecube.cfg &
cubepid=`echo $!`
echo CUBE pid : $cubepid \n


